### PR TITLE
PCT-540 Agent does not support old password authentication

### PR DESCRIPTION
**Pull request by cfsalguero**
Old password is being disabled before running GRANTs because
if we create/update a user's password while old_passworrds is
enabled, it doesn't work as expected and then the agent is not
able to connect to the db.

### CODE REVIEW

**Comment by arvenil** [comment]
Is there an easy way to test this? :) If not then :+1:

**Comment by arvenil** [comment]
@vadimtk @daniel-nichter Btw what's about this `old_passwords` config? According to http://dev.mysql.com/doc/refman/5.6/en/password-hashing.html this is compatibility option with MySQL 4.1? Officially we support MySQL > 5.1? So what are cases people have this still enabled in 5.1? Upgraded from MySQL < 4.1 and didn't migrate passwords?

**Comment by cfsalguero** [comment]
Don't think that's the case.
To reproduce the problem:
1) Enable old_passwords
2) Create a new user and set its password
3) Try to login (from a Go program). It will fail. Logins from cli works Ok

**Comment by arvenil** [comment]
Yes, I'm simply asking why anyone would like to enable "old_passwords"? I just wonder why we care about old_passwords option since it looks like really old compatibility flag. Just a general question.

**Comment by vadimtk** [comment]
Kamil,

Surprisingly we still see many customers running MySQL with old_passwords
option,
they used it for migration from previous versions of MySQL and to keep
compatibility with applications.



On Wed, Feb 18, 2015 at 8:15 AM, Kamil Dziedzic <notifications@github.com>
wrote:

> Yes, I'm simply asking why anyone would like to enable "old_passwords"? I
> just wonder why we care about old_passwords option since it looks like
> really old compatibility flag. Just a general question.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/percona/percona-agent/pull/138#issuecomment-74892604>.
>



-- 
Vadim Tkachenko, CTO, Percona
Phone +1-925-400-7377,  Skype: vadimtk153

Percona Cloud Tools - to make MySQL Performance Easy
https://clould.percona.com

**Comment by arvenil** [comment]
Thanks @vadimtk - interesting lesson :) 4.1.1 released on `2003-12-01` :) http://dev.mysql.com/doc/refman/4.1/en/news-4-1-1.html `C.1.25 Changes in MySQL 4.1.1 (2003-12-01)`

**Pull request merged**
